<?php
			if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
          'key' => 'group_61890e98dcd83',
          'title' => 'Blog Posts',
          'fields' => array(
            array(
              'key' => 'field_6189da020234e',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 'Latest News',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_61890e9df0129',
              'label' => 'Category',
              'name' => 'category',
              'type' => 'taxonomy',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '80',
                'class' => '',
                'id' => '',
              ),
              'taxonomy' => 'category',
              'field_type' => 'multi_select',
              'allow_null' => 0,
              'add_term' => 0,
              'save_terms' => 0,
              'load_terms' => 0,
              'return_format' => 'id',
              'multiple' => 0,
            ),
            array(
              'key' => 'field_61890ec0f012a',
              'label' => 'Show Featured Image',
              'name' => 'show_featured_image',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 1,
              'ui' => 1,
              'ui_on_text' => 'Show',
              'ui_off_text' => 'Hide',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/blog-posts',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_6189e0100e84b',
          'title' => 'Careers',
          'fields' => array(
            array(
              'key' => 'field_6189e013a1b8d',
              'label' => 'Apply by',
              'name' => 'apply_by',
              'type' => 'date_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'display_format' => 'd.m.Y',
              'return_format' => 'd/m/Y',
              'first_day' => 1,
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'post_category',
                'operator' => '==',
                'value' => 'category:careers',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_6177f444db1be',
          'title' => 'Hero',
          'fields' => array(
            array(
              'key' => 'field_6182e7e9d5099',
              'label' => 'Is Full Screen?',
              'name' => 'is_full_screen',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 0,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array(
              'key' => 'field_6177f449dc3c6',
              'label' => 'Hero Title',
              'name' => 'hero_title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_6177f4c0dc3c7',
              'label' => 'Hero Subtitle',
              'name' => 'hero_subtitle',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_61782e68b84e5',
              'label' => 'Hero Image',
              'name' => 'hero_image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'full',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array(
              'key' => 'field_6180a1b5b1148',
              'label' => 'Hero Video',
              'name' => 'hero_video_url',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/hero',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_618241e3f34e4',
          'title' => 'Image Banner',
          'fields' => array(
            array(
              'key' => 'field_618241e8f5445',
              'label' => 'Image',
              'name' => 'image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array(
              'key' => 'field_61824200d0d8b',
              'label' => 'Height',
              'name' => 'height',
              'type' => 'number',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 400,
              'placeholder' => '',
              'prepend' => '',
              'append' => 'px',
              'min' => '',
              'max' => '',
              'step' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/image-banner',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_6189c08d47f84',
          'title' => 'Page Settings',
          'fields' => array(
            array(
              'key' => 'field_6189c0a23ee0c',
              'label' => 'Show Map',
              'name' => 'show_map',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '10',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array(
              'key' => 'field_6189c0db3ee0d',
              'label' => 'Show Contact Form',
              'name' => 'show_form',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '10',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array(
              'key' => 'field_6189c345c0128',
              'label' => 'Contact From CTA',
              'name' => 'contact_form_cta',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_6189c0db3ee0d',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '30',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 'Have a project in mind? Leave us a message',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_6189c3ddc0129',
              'label' => 'Button Text',
              'name' => 'contact_form_button_text',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_6189c0db3ee0d',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '10',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 'Let\'s talk',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_6189c1383ee0e',
              'label' => 'Contact Form Shortcode',
              'name' => 'contact_form_shortcode',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_6189c0db3ee0d',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '30',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_6189c1543ee0f',
              'label' => 'Opened by Default',
              'name' => 'opened_by_default',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_6189c0db3ee0d',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '10',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
              ),
            ),
            array(
              array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_6179c7e4b9372',
          'title' => 'Section',
          'fields' => array(
            array(
              'key' => 'field_6179c7ea120d6',
              'label' => 'Background Color',
              'name' => 'bg_color',
              'type' => 'radio',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'bg-white' => 'White',
                'bg-gray' => 'Gray',
                'bg-light-2' => 'Smoke Gray',
                'bg-salmon' => 'Salmon',
                'bg-dark' => 'Dark Blue',
                'bg-dark-2' => 'Dark 2',
              ),
              'allow_null' => 0,
              'other_choice' => 0,
              'default_value' => '',
              'layout' => 'vertical',
              'return_format' => 'value',
              'save_other_choice' => 0,
            ),
            array(
              'key' => 'field_61879fbc96340',
              'label' => 'Remove padding?',
              'name' => 'padding',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/section',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_61843b95d446e',
          'title' => 'Team Members',
          'fields' => array(
            array(
              'key' => 'field_61843b9a2e182',
              'label' => 'Title',
              'name' => 'title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_61843be42e183',
              'label' => 'Phone Number',
              'name' => 'phone',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_61843c102e184',
              'label' => 'Email Address',
              'name' => 'email',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_61843c3094809',
              'label' => 'LinkedIn Profile URL',
              'name' => 'linkedin',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
            array(
              'key' => 'field_61843c439480a',
              'label' => 'Highlights',
              'name' => 'highlights',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array(
              'key' => 'field_61843c529480b',
              'label' => 'Education',
              'name' => 'education',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => '',
              'sub_fields' => array(
                array(
                  'key' => 'field_61843c5f9480c',
                  'label' => 'Item',
                  'name' => 'item',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
              ),
            ),
            array(
              'key' => 'field_61843c679480d',
              'label' => 'Languages',
              'name' => 'languages',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_61843c809480e',
              'label' => 'Career',
              'name' => 'career',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => '',
              'sub_fields' => array(
                array(
                  'key' => 'field_61843c899480f',
                  'label' => 'Item',
                  'name' => 'item',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
              ),
            ),
            array(
              'key' => 'field_61843c8d94810',
              'label' => 'Memberships',
              'name' => 'memberships',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => '',
              'sub_fields' => array(
                array(
                  'key' => 'field_61843c9894811',
                  'label' => 'Item',
                  'name' => 'item',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
              ),
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'team_member',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_6181b102a0352',
          'title' => 'Text and Media',
          'fields' => array(
            array(
              'key' => 'field_618244821f4a0',
              'label' => 'Text Column Width',
              'name' => 'text_column_width',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'col-md-2' => '2/12',
                'col-md-3' => '3/12',
                'col-md-4' => '4/12',
                'col-md-5' => '5/12',
                'col-md-6' => '6/12',
                'col-md-7' => '7/12',
                'col-md-8' => '8/12',
                'col-md-9' => '9/12',
                'col-md-10' => '10/12',
              ),
              'default_value' => 'col-md-8',
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
            array(
              'key' => 'field_618244c51f4a1',
              'label' => 'Media Column Width',
              'name' => 'media_column_width',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'col-md-2' => '2/12',
                'col-md-3' => '3/12',
                'col-md-4' => '4/12',
                'col-md-5' => '5/12',
                'col-md-6' => '6/12',
                'col-md-7' => '7/12',
                'col-md-8' => '8/12',
                'col-md-9' => '9/12',
                'col-md-10' => '10/12',
              ),
              'default_value' => 'col-md-4',
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
            array(
              'key' => 'field_6187bab8c596c',
              'label' => 'Column Order (Desktop)',
              'name' => 'column_order',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => 'Image',
              'ui_off_text' => 'Image',
            ),
            array(
              'key' => 'field_618a19b340d33',
              'label' => 'Column Order (Mobile)',
              'name' => 'column_order_mobile',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => 'Image',
              'ui_off_text' => 'Image',
            ),
            array(
              'key' => 'field_6181b11515955',
              'label' => 'Text Column Content',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 0,
              'delay' => 0,
            ),
            array(
              'key' => 'field_6187856678be8',
              'label' => 'Link Text',
              'name' => 'link_text',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array(
              'key' => 'field_6187857c78bea',
              'label' => 'Link Target',
              'name' => 'link_target',
              'type' => 'page_link',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'post_type' => '',
              'taxonomy' => '',
              'allow_null' => 0,
              'allow_archives' => 1,
              'multiple' => 0,
            ),
            array(
              'key' => 'field_6181b13a15956',
              'label' => 'Image 1',
              'name' => 'image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '30',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array(
              'key' => 'field_618a197340d32',
              'label' => 'Image is a logo?',
              'name' => 'is_logo',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array(
              'key' => 'field_61877cb3458b0',
              'label' => 'Image 2',
              'name' => 'image_2',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_618a197340d32',
                    'operator' => '!=',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'medium',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/text-and-media',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_618426355e328',
          'title' => 'Text and Slider',
          'fields' => array(
            array(
              'key' => 'field_6184263d63aa0',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array(
              'key' => 'field_6184264663aa1',
              'label' => 'Slider',
              'name' => 'slider',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'table',
              'button_label' => '',
              'sub_fields' => array(
                array(
                  'key' => 'field_6184265763aa2',
                  'label' => 'Slide Content',
                  'name' => 'slide_content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
              ),
            ),
            array(
              'key' => 'field_618427e06bf93',
              'label' => 'Text Column Width',
              'name' => 'text_column_width',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'col-md-2' => '2/12',
                'col-md-3' => '3/12',
                'col-md-4' => '4/12',
                'col-md-5' => '5/12',
                'col-md-6' => '6/12',
                'col-md-7' => '7/12',
                'col-md-8' => '8/12',
                'col-md-9' => '9/12',
                'col-md-10' => '10/12',
              ),
              'default_value' => 'col-md-4',
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
            array(
              'key' => 'field_618427ef6bf94',
              'label' => 'Slider Column Width',
              'name' => 'slider_column_width',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'col-md-2' => '2/12',
                'col-md-3' => '3/12',
                'col-md-4' => '4/12',
                'col-md-5' => '5/12',
                'col-md-6' => '6/12',
                'col-md-7' => '7/12',
                'col-md-8' => '8/12',
                'col-md-9' => '9/12',
                'col-md-10' => '10/12',
              ),
              'default_value' => 'col-md-7',
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'return_format' => 'value',
              'ajax' => 0,
              'placeholder' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/text-and-slider',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        acf_add_local_field_group(array(
          'key' => 'group_6181a8fda1740',
          'title' => 'Text Boxes',
          'fields' => array(
            array(
              'key' => 'field_6181a90d54ea8',
              'label' => 'Text Boxes',
              'name' => 'text_boxes',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'block',
              'button_label' => '',
              'sub_fields' => array(
                array(
                  'key' => 'field_6181a91954ea9',
                  'label' => 'Text Box Content',
                  'name' => 'text_box_content',
                  'type' => 'wysiwyg',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '60',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'tabs' => 'all',
                  'toolbar' => 'full',
                  'media_upload' => 1,
                  'delay' => 0,
                ),
                array(
                  'key' => 'field_6181ac4d78377',
                  'label' => 'Text Box Width',
                  'name' => 'text_box_width',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'col-md-4' => '4/12',
                    'col-md-8' => '8/12',
                    'col-md-12' => '12/12',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'vertical',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_6181abe378376',
                  'label' => 'Text Box Color',
                  'name' => 'text_box_color',
                  'type' => 'radio',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'bg-white' => 'White',
                    'bg-grey' => 'Grey',
                    'bg-salmon' => 'Salmon',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => 'bg-white',
                  'layout' => 'vertical',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_6187835865297',
                  'label' => 'Read More Link',
                  'name' => 'read_more_link',
                  'type' => 'page_link',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => '',
                  'taxonomy' => '',
                  'allow_null' => 0,
                  'allow_archives' => 1,
                  'multiple' => 0,
                ),
                array(
                  'key' => 'field_618a4ed1dfbdf',
                  'label' => 'Replace text with image',
                  'name' => 'image',
                  'type' => 'image',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'url',
                  'preview_size' => 'medium',
                  'library' => 'all',
                  'min_width' => '',
                  'min_height' => '',
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => '',
                ),
              ),
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/text-boxes',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
        ));
        
        endif;